In [1]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [2]:
my_arr = np.arange(100000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 1.73 ms, sys: 1.55 ms, total: 3.28 ms
Wall time: 2.14 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 626 ms, sys: 186 ms, total: 812 ms
Wall time: 920 ms


In [5]:
data = np.random.randn(2, 3)
data

array([[ 1.75769692, -0.23270612, -2.90195209],
       [-0.84174883, -0.08316655, -1.5449781 ]])

In [6]:
data * 10

array([[ 17.57696922,  -2.32706117, -29.01952086],
       [ -8.41748829,  -0.83166548, -15.44978101]])

In [7]:
data + data

array([[ 3.51539384, -0.46541223, -5.80390417],
       [-1.68349766, -0.1663331 , -3.0899562 ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

#       Creating ndarrays

In [10]:
data1 = [6, 7.5, 8, 0, 1]

In [11]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
arr1.dtype

dtype('float64')

In [16]:
arr2.dtype

dtype('int64')

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2))

array([[[ 1.49166815e-154, -1.49457933e-154],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 1.49166815e-154,  1.49166815e-154],
        [ 8.26571670e-072,  6.15885706e+170],
        [ 3.99910963e+252,  8.34404819e-309]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1 = np.array([1, 2, 3])
arr1.dtype

dtype('int64')

# Data Types for ndarrays

In [22]:
arr2 = np.array([1, 2, 3])
arr2.dtype

dtype('int64')

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [24]:
float_arr =  arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [28]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
empty_unit32 = np.empty(8, dtype = 'u4')
empty_unit32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

# Arithmetic with numPy Arrays

In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [32]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [34]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [36]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# Indexing and Slicing

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[5]

5

In [39]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12

In [41]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice = arr[5:8]

In [43]:
arr_slice

array([12, 12, 12])

In [44]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [45]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [47]:
arr2d[0][2]

3

In [48]:
arr2d[0, 2]

3

In [49]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d[1, 0]

array([7, 8, 9])

In [54]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
x[0]

array([7, 8, 9])

# Indexing with slices

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [61]:
arr2d[1,:2]

array([4, 5])

In [62]:
arr2d[:2, 2]

array([3, 6])

In [63]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [64]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

In [66]:
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [67]:
data

array([[ 1.39385823,  0.588045  , -0.63585119, -2.19665117],
       [ 1.39850224, -1.54716221, -0.64422674,  0.60032987],
       [-0.73547001, -0.37711481, -0.36573096,  0.73801342],
       [ 0.71236446,  0.00932948, -3.07964044, -0.28983244],
       [ 0.33419542,  0.07820812,  0.88880323,  1.49678941],
       [-0.89394851,  0.29505976, -0.3495177 ,  1.10332331],
       [ 0.55145308, -0.35371772,  1.071196  ,  0.59312525]])

In [68]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [69]:
data[names == 'Bob']

array([[ 1.39385823,  0.588045  , -0.63585119, -2.19665117],
       [ 0.71236446,  0.00932948, -3.07964044, -0.28983244]])

In [70]:
data[names == 'Bob', 2:]

array([[-0.63585119, -2.19665117],
       [-3.07964044, -0.28983244]])

In [71]:
data[names == 'Bob', 3]

array([-2.19665117, -0.28983244])

In [72]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [73]:
data[~(names == 'Bob')]

array([[ 1.39850224, -1.54716221, -0.64422674,  0.60032987],
       [-0.73547001, -0.37711481, -0.36573096,  0.73801342],
       [ 0.33419542,  0.07820812,  0.88880323,  1.49678941],
       [-0.89394851,  0.29505976, -0.3495177 ,  1.10332331],
       [ 0.55145308, -0.35371772,  1.071196  ,  0.59312525]])

In [74]:
cond = names == 'Bob'
data[~cond]

array([[ 1.39850224, -1.54716221, -0.64422674,  0.60032987],
       [-0.73547001, -0.37711481, -0.36573096,  0.73801342],
       [ 0.33419542,  0.07820812,  0.88880323,  1.49678941],
       [-0.89394851,  0.29505976, -0.3495177 ,  1.10332331],
       [ 0.55145308, -0.35371772,  1.071196  ,  0.59312525]])

In [75]:
mask = (names =='Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [76]:
data[mask]

array([[ 1.39385823,  0.588045  , -0.63585119, -2.19665117],
       [-0.73547001, -0.37711481, -0.36573096,  0.73801342],
       [ 0.71236446,  0.00932948, -3.07964044, -0.28983244],
       [ 0.33419542,  0.07820812,  0.88880323,  1.49678941]])

In [77]:
data[data < 0] = 0
data

array([[1.39385823, 0.588045  , 0.        , 0.        ],
       [1.39850224, 0.        , 0.        , 0.60032987],
       [0.        , 0.        , 0.        , 0.73801342],
       [0.71236446, 0.00932948, 0.        , 0.        ],
       [0.33419542, 0.07820812, 0.88880323, 1.49678941],
       [0.        , 0.29505976, 0.        , 1.10332331],
       [0.55145308, 0.        , 1.071196  , 0.59312525]])

In [78]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.39850224, 0.        , 0.        , 0.60032987],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.29505976, 0.        , 1.10332331],
       [0.55145308, 0.        , 1.071196  , 0.59312525]])

# Fancy Indexing

In [79]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [80]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [81]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [82]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [83]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [84]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [85]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [87]:
arr = np.random.randn(6, 3)
arr

array([[ 1.09738688, -0.36684184, -0.36947384],
       [-0.22122379, -0.03269385, -0.20326236],
       [ 2.56994868,  0.34785102, -0.37310655],
       [-0.64619023,  0.6241284 ,  1.44698171],
       [-0.44733533, -1.18329361,  0.92281498],
       [ 1.0081691 ,  1.01367867, -0.29141559]])

In [88]:
np.dot(arr.T, arr)

array([[ 9.49190979,  1.64660738, -2.96098335],
       [ 1.64660738,  3.07390664, -0.47186206],
       [-2.96098335, -0.47186206,  3.34730161]])

In [89]:
arr = np.arange(16).reshape(2, 2, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [91]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions: Fast Element-Wise Array Functions

In [93]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [95]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [96]:
x = np.random.randn(8)

In [97]:
y = np.random.randn(8)

In [98]:
x

array([-0.59310054,  0.03172388,  1.95890263,  0.34699837,  0.38692375,
       -0.06721436,  0.06966421,  0.64006178])

In [99]:
y

array([-0.13220771,  2.37627456,  0.56118184,  1.68608558,  0.36370954,
        0.28987655, -1.0833674 ,  1.87662299])

In [100]:
np.maximum(x, y)

array([-0.13220771,  2.37627456,  1.95890263,  1.68608558,  0.38692375,
        0.28987655,  0.06966421,  1.87662299])

In [101]:
arr = np.random.randn(7) * 5
arr

array([ 3.01939602,  8.1185822 , -2.43102733, -1.32509142,  8.45236534,
        2.03725993,  4.63200166])

In [102]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.01939602,  0.1185822 , -0.43102733, -0.32509142,  0.45236534,
        0.03725993,  0.63200166])

In [103]:
whole_part

array([ 3.,  8., -2., -1.,  8.,  2.,  4.])

In [104]:
arr

array([ 3.01939602,  8.1185822 , -2.43102733, -1.32509142,  8.45236534,
        2.03725993,  4.63200166])

In [107]:
arr

array([1.73764094, 2.84931258,        nan,        nan, 2.90729519,
       1.42732615, 2.15220855])

# Array-Oriented Programming with Arrays